- build.gradle
- database/app/build.gradle
- database/app/src/main/AndroidManifest.xml
- database/app/src/main/java/com/google/firebase/referencecode/database/KotlinActivity.kt
- database/app/src/main/java/com/google/firebase/referencecode/database/MainActivity.java
- database/app/src/main/java/com/google/firebase/referencecode/database/interfaces/ActivityInterface.java
Fixed #5 
P.S. @samtstern should we add code for ChildEventListener as well?
Signed-off-by: the-dagger <harshithdwivedi@gmail.com>
> feat : kotlinized database snippet

- auth/app/build.gradle
- auth/app/src/main/AndroidManifest.xml
- auth/app/src/main/java/com/google/firebase/quickstart/auth/KotlinMainActivity.kt
- auth/app/src/main/java/com/google/firebase/quickstart/auth/MainActivity.java
- auth/app/src/main/java/com/google/firebase/quickstart/auth/interfaces/MainActivityInterface.java
- build.gradle
Fixed #12 
@samtstern Please review.
P.S. AS seem to have bumped up the kotlin version, let me know if you want me to downgrade it to the earlier version.
Signed-off-by: the-dagger <harshithdwivedi@gmail.com>
> feat : kotlinize the auth activity

- auth/app/src/main/java/com/google/firebase/quickstart/auth/MainActivity.java
Replaced deprecated getToken() with getIdToken()
> Updated comment referencing deprecated getToken()

- storage/app/build.gradle
- storage/app/src/main/AndroidManifest.xml
- storage/app/src/main/java/com/google/firebase/referencecode/storage/KotlinStorageActivity.kt
- storage/app/src/main/java/com/google/firebase/referencecode/storage/StorageActivity.java
- storage/app/src/main/java/com/google/firebase/referencecode/storage/interfaces/StorageActivityInterface.java
First PR for #24 
- Add Kotlin Support to build.gradle
- Create interface to keep both java and kotlin Activities in sync
- Update Java Activity to implement the interface and override their methods
- Create Kotlin Activity
- Add Kotlin Activity to AndroidManifest
> feat: Create Storage Sample in Kotlin

- tasks/app/build.gradle
- tasks/app/src/main/AndroidManifest.xml
- tasks/app/src/main/java/com/google/firebase/quickstart/tasks/KotlinMainActivity.kt
- tasks/app/src/main/java/com/google/firebase/quickstart/tasks/MainActivity.java
- tasks/app/src/main/java/com/google/firebase/quickstart/tasks/interfaces/MainActivityInterface.java
- Add Kotlin Support
- Create interface to keep both java and kotlin Activities in sync
- Update Java Activity to implement the interface and override their methods
- Create Kotlin Activity
- Add Kotlin Activity to AndroidManifest
Second PR for #24
>  feat: Create Tasks Sample in Kotlin

- firebaseoptions/app/build.gradle
- firebaseoptions/app/src/main/AndroidManifest.xml
- firebaseoptions/app/src/main/java/devrel/firebase/google/com/firebaseoptions/KotlinMainActivity.kt
- Add Kotlin Support
- Create Kotlin Activity
- Add Kotlin Activity to AndroidManifest
Third PR for #24
>  feat: Create FirebaseOptions Sample in Kotlin

- dynamic-links/app/build.gradle
- dynamic-links/app/src/main/AndroidManifest.xml
- dynamic-links/app/src/main/java/com/google/firebase/quickstart/dynamiclinks/KotlinMainActivity.kt
- dynamic-links/app/src/main/java/com/google/firebase/quickstart/dynamiclinks/MainActivity.java
- dynamic-links/app/src/main/java/com/google/firebase/quickstart/dynamiclinks/interfaces/MainActivityInterface.java
- Add Kotlin Support to build.gradle
- Create interface to keep both java and kotlin Activities in sync
- Update Java Activity to implement the interface and override their methods
- Create Kotlin Activity
- Add Kotlin Activity to AndroidManifest
- Correct minor typo on `shortenLongLink()` method from Java Activity
Last PR to fix #24
>  feat: Create Dynamic Links Sample in Kotlin

- firestore/app/build.gradle
- firestore/app/google-services.json
- firestore/app/src/main/java/com/google/example/firestore/DocSnippets.java
- firestore/app/src/main/java/com/google/example/firestore/DocSnippetsInterface.java
- firestore/app/src/main/java/com/google/example/firestore/SolutionArrays.java
- firestore/app/src/main/java/com/google/example/firestore/kotlin/DocSnippets.kt
See https://github.com/firebase/snippets-ios/pull/12
> Add array data and queries

- instanceid/app/build.gradle
- messaging/app/build.gradle
- test-lab/app/build.gradle
See #45 which discovered the failure
> Fix build failure

- appindexing/app/src/main/AndroidManifest.xml
- appindexing/app/src/main/java/com/google/firebase/example/appindexing/KotlinAppIndexingUpdateReceiver.kt
- appindexing/app/src/main/java/com/google/firebase/example/appindexing/KotlinAppIndexingUpdateService.kt
- appindexing/app/src/main/java/com/google/firebase/example/appindexing/KotlinMainActivity.kt
- appindexing/app/src/main/java/com/google/firebase/example/appindexing/KotlinMeasureActivity.kt
- appindexing/app/src/main/java/com/google/firebase/example/appindexing/MainActivity.java
- appindexing/app/src/main/java/com/google/firebase/example/appindexing/MeasureActivity.java
- appindexing/app/src/main/java/com/google/firebase/example/appindexing/interfaces/MainActivityInterface.kt
- appindexing/app/src/main/java/com/google/firebase/example/appindexing/interfaces/MeasureActivityInterface.kt
@samtstern I seem to have missed out on the appindexing module in the earlier PR, sorry about that!
> feat : kotlinize indexing snippets

- auth/app/src/main/java/com/google/firebase/quickstart/auth/MainActivity.java
Noticed this as I was browsing the docs.
> remove dangling semicolon

- database/app/src/main/java/com/google/firebase/referencecode/database/kotlin/OfflineActivity.kt
Fixes the highlighted issues in the last commit @samtstern 
Signed-off-by: the-dagger <harshithdwivedi@gmail.com>
> refactor : optimize kotlin snippets in OfflineActivity

- messaging/app/src/main/java/com/google/firebase/example/messaging/MainActivity.java
- messaging/app/src/main/java/com/google/firebase/example/messaging/kotlin/MainActivity.kt
Update the domain used for sending upstream messages to `@fcm.googleapis.com` instead of `@gcm.googleapis.com`.
> Use fcm for upstream

- firestore/app/src/main/java/com/google/example/firestore/kotlin/DocSnippets.kt
- inappmessaging/app/build.gradle
- inappmessaging/app/src/main/AndroidManifest.xml
- inappmessaging/app/src/main/java/com/google/firebase/example/inappmessaging/MainActivity.java
- inappmessaging/app/src/main/java/com/google/firebase/example/inappmessaging/MyClickListener.java
- inappmessaging/app/src/main/java/com/google/firebase/example/inappmessaging/kotlin/MainActivity.kt
- inappmessaging/app/src/main/java/com/google/firebase/example/inappmessaging/kotlin/MyClickListener.kt
- inappmessaging/app/src/main/res/values/strings.xml
> FIAM Snippets

- mlkit/app/src/main/java/com/google/firebase/example/mlkit/kotlin/CustomModelActivity.kt
- mlkit/app/src/main/java/com/google/firebase/example/mlkit/kotlin/FaceDetectionActivity.kt
- mlkit/app/src/main/java/com/google/firebase/example/mlkit/kotlin/ImageLabelingActivity.kt
- mlkit/app/src/main/java/com/google/firebase/example/mlkit/kotlin/LandmarkRecognitionActivity.kt
- mlkit/app/src/main/java/com/google/firebase/example/mlkit/kotlin/TextRecognitionActivity.kt
Use lambda functions and `listOf()` for code simplicity on the kotlin snippets.
> refactor: use lambda functions and listOf() on mlkit snippets

- perf/app/src/main/java/com/google/firebase/example/perf/MainActivity.java
- perf/app/src/main/java/com/google/firebase/example/perf/kotlin/MainActivity.kt
Starting in Remote Config [v16.5.0](https://firebase.google.com/support/release-notes/android#version_1650), some functions were deprecated and alternative functions were added, but our Performance Monitor snippets are still using the deprecated ones.
This PR should replace the deprecated functions with their alternatives in our PerfMon snippets.
Notice that I've added Completion Listeners and Continuations because of the async behavior of the new functions.
> refactor(perf): update deprecated remote config functions

- predictions/app/src/main/java/com/google/firebase/example/predictions/ConditionalAdsActivity.java
- predictions/app/src/main/java/com/google/firebase/example/predictions/MainActivity.java
- predictions/app/src/main/java/com/google/firebase/example/predictions/OptimizePromotionsActivity.java
- predictions/app/src/main/java/com/google/firebase/example/predictions/PreventChurnActivity.java
- predictions/app/src/main/java/com/google/firebase/example/predictions/kotlin/ConditionalAdsActivity.kt
- predictions/app/src/main/java/com/google/firebase/example/predictions/kotlin/MainActivity.kt
- predictions/app/src/main/java/com/google/firebase/example/predictions/kotlin/OptimizePromotionsActivity.kt
- predictions/app/src/main/java/com/google/firebase/example/predictions/kotlin/PreventChurnActivity.kt
This is the same as #171 , but now in our Firebase Predictions snippets.
> refactor(predictions): update deprecated remote config functions

- dynamic-links/app/build.gradle
- dynamic-links/app/src/main/java/com/google/firebase/quickstart/dynamiclinks/kotlin/MainActivity.kt
- dynamic-links/app/src/main/java/com/google/firebase/quickstart/dynamiclinks/kotlin/ReferralActivity.kt
This PR should convert the Dynamic Links snippets in #174 to KTX.
The `dynamic-links-ktx` library was released last friday and the docs are yet to be added to firebaseopensource.com (see firebase/firebase-android-sdk/pull/971)
> Dynamic Links + KTX

- analytics/app/src/main/java/com/google/firebase/example/analytics/MainActivity.java
- analytics/app/src/main/java/com/google/firebase/example/analytics/kotlin/MainActivity.kt
Based on:
https://github.com/firebase/snippets-ios/pull/153/files
cc @morganchen12
> Enhanced Ecommerce Snippets

- auth/app/build.gradle
- auth/app/src/main/java/com/google/firebase/quickstart/auth/kotlin/MainActivity.kt
- dynamic-links/app/build.gradle
- dynamic-links/app/src/main/java/com/google/firebase/quickstart/dynamiclinks/kotlin/ReferralActivity.kt
- tasks/app/build.gradle
- tasks/app/src/main/java/com/google/firebase/quickstart/tasks/kotlin/MainActivity.kt
[Firebase Auth KTX](https://firebase.google.com/docs/reference/kotlin/com/google/firebase/auth/ktx/package-summary) was recently released. This should update our snippets to use it instead.
Additionally, I've replaced some of the null-safe expressions with `!!` because I'm afraid beginners who copy code from the Documentation might think their code is not being executed, when in reality some properties (like `currentUser`) are null.
> refactor(auth): update code to use Firebase Auth KTX

- analytics/app/src/main/java/com/google/firebase/example/analytics/kotlin/MainActivity.kt
Bringing the new `FirebaseAnalytics.logEvent()` function to our Docs :)
> refactor(analytics): update code to use logEvent() KTX

- crashlytics/app/build.gradle
- crashlytics/app/src/main/java/com/google/firebase/example/crashlytics/MainActivity.java
- crashlytics/app/src/main/java/com/google/firebase/example/crashlytics/kotlin/MainActivity.kt
Move Crashlytics snippets to KTX
> Crashlytics KTX snippets

- mlkit/app/src/main/java/com/google/firebase/example/mlkit/BarcodeScanningActivity.java
- mlkit/app/src/main/java/com/google/firebase/example/mlkit/FaceDetectionActivity.java
- mlkit/app/src/main/java/com/google/firebase/example/mlkit/ImageLabelingActivity.java
- mlkit/app/src/main/java/com/google/firebase/example/mlkit/LandmarkRecognitionActivity.java
- mlkit/app/src/main/java/com/google/firebase/example/mlkit/TextRecognitionActivity.java
- mlkit/app/src/main/java/com/google/firebase/example/mlkit/kotlin/BarcodeScanningActivity.kt
- mlkit/app/src/main/java/com/google/firebase/example/mlkit/kotlin/FaceDetectionActivity.kt
- mlkit/app/src/main/java/com/google/firebase/example/mlkit/kotlin/ImageLabelingActivity.kt
- mlkit/app/src/main/java/com/google/firebase/example/mlkit/kotlin/LandmarkRecognitionActivity.kt
- mlkit/app/src/main/java/com/google/firebase/example/mlkit/kotlin/TextRecognitionActivity.kt
- tasks/app/src/main/java/com/google/firebase/quickstart/tasks/MainActivity.java
- tasks/app/src/main/java/com/google/firebase/quickstart/tasks/kotlin/MainActivity.kt
Hoping to fix #192 
I'm guessing this requires a change on the devsite's side before it can be merged.
> chore: change region tags prefixed with 'run_'

- installations/app/src/main/java/com/google/samples/snippet/MainActivity.java
- installations/app/src/main/java/com/google/samples/snippet/kotlin/MainActivity.kt
Add installations delete snippets. Also update task completion handlers to check for success and log errors if not successful.
> Add installations delete snippets

- database/app/src/main/java/com/google/firebase/referencecode/database/EmulatorSuite.java
- database/app/src/main/java/com/google/firebase/referencecode/database/kotlin/EmulatorSuite.kt
- firestore/app/src/main/java/com/google/example/firestore/EmulatorSuite.java
- firestore/app/src/main/java/com/google/example/firestore/kotlin/EmulatorSuite.kt
- functions/app/src/main/java/devrel/firebase/google/com/functions/MainActivity.java
- functions/app/src/main/java/devrel/firebase/google/com/functions/kotlin/MainActivity.kt
> Move to useEmulator API

- firestore/app/src/main/java/com/google/example/firestore/DocSnippets.java
- firestore/app/src/main/java/com/google/example/firestore/kotlin/DocSnippets.kt
> Firestore != queries

- dynamic-links/app/src/main/java/com/google/firebase/quickstart/dynamiclinks/kotlin/MainActivity.kt
- dynamic-links/app/src/main/java/com/google/firebase/quickstart/dynamiclinks/kotlin/ReferralActivity.kt
This PR should:
- Make use of the new Kotlin Destructuring Declarations added in the latest version of FDL KTX.
- Make use of Kotlin's scope functions (`apply` and `let`) to simplify the snippets.
- Replace String concatenation with Kotlin's String templates.
> refactor(dynamic-links): improve the Kotlin snippets

- messaging/app/build.gradle
- messaging/app/src/main/java/com/google/firebase/example/messaging/kotlin/MainActivity.kt
> feat(fcm): use Firebase KTX on the kotlin snippets

- firestore/app/build.gradle
- firestore/app/src/main/java/com/google/example/firestore/SolutionGeoqueries.java
- firestore/app/src/main/java/com/google/example/firestore/kotlin/SolutionGeoqueries.kt
Android version of: https://github.com/firebase/snippets-web/pull/52
> Add snippets for Firestore geoqueries

- firestore/app/src/main/java/com/google/example/firestore/SolutionGeoqueries.java
- firestore/app/src/main/java/com/google/example/firestore/kotlin/SolutionGeoqueries.kt
See:
https://twitter.com/gdemiollis/status/1341141597522673665
https://github.com/firebase/geofire-android/pull/11
> Fix distance units

- firestore/app/src/main/java/com/google/example/firestore/SolutionGeoqueries.java
- firestore/app/src/main/java/com/google/example/firestore/kotlin/SolutionGeoqueries.kt
Follow up to #269 
Test to ensure correctness:
https://github.com/firebase/geofire-android/pull/12
> Another geoutils fix

- database/app/src/main/java/com/google/firebase/referencecode/database/ReadAndWriteSnippets.java
- database/app/src/main/java/com/google/firebase/referencecode/database/kotlin/ReadAndWriteSnippets.kt
Follow up to #275 by @rosariopfernandes
> Clean up some migrated database snippets

- perf/app/build.gradle
- perf/app/src/main/java/com/google/firebase/example/perf/kotlin/MainActivity.kt
Bringing Firebase KTX to our Performance Monitor snippets 🎉
> refactor(perfmon): use Firebase KTX in our code snippets

- scripts/checksnippets.py
I guess GitHub actions updated?
> Move scripts to python3

- database/app/src/main/java/com/google/firebase/referencecode/database/ReadAndWriteSnippets.java
- database/app/src/main/java/com/google/firebase/referencecode/database/kotlin/ReadAndWriteSnippets.kt
Added code snippets for RTDB's increment() operation, replacing two transactions with a single multi-path update.
> Added RTDB increment snippets

- auth/app/build.gradle
- auth/app/src/main/java/com/google/firebase/quickstart/auth/FirebaseUIActivity.java
- auth/app/src/main/java/com/google/firebase/quickstart/auth/kotlin/FirebaseUIActivity.kt
This is newly supported in `firebase-ui-auth` version `7.2.0`
> Use ActivityResultLauncher in FirebaseUI Auth Snippets

- analytics/app/src/main/java/com/google/firebase/example/analytics/MainActivity.java
- analytics/app/src/main/java/com/google/firebase/example/analytics/kotlin/MainActivity.kt
fix for #324 update ironSource snippet
> fix: update adunitname in Firebase to map to instanceName in ironSource

- functions/app/src/main/java/devrel/firebase/google/com/functions/MainActivity.java
- functions/app/src/main/java/devrel/firebase/google/com/functions/kotlin/MainActivity.kt
Bringing over Cloud Functions snippets from quickstart-android
> port functions snippets from quickstart-android

- messaging/app/build.gradle
- messaging/app/src/main/java/com/google/firebase/example/messaging/MainActivity.java
- messaging/app/src/main/java/com/google/firebase/example/messaging/MyFirebaseMessagingService.java
- messaging/app/src/main/java/com/google/firebase/example/messaging/kotlin/MainActivity.kt
- messaging/app/src/main/java/com/google/firebase/example/messaging/kotlin/MyFirebaseMessagingService.kt
This PR should bring the FCM snippets from quickstart-android to this repository.
> port FCM snippets from quickstart-android

- messaging/app/build.gradle
- messaging/app/src/main/java/com/google/firebase/example/messaging/MainActivity.java
- messaging/app/src/main/java/com/google/firebase/example/messaging/kotlin/MainActivity.kt
Add snippets of requesting and handling the result of a POST_NOTIFICATION permission request.
> feat: demonstrate asking for post notification permission

- appcheck/app/build.gradle
- appcheck/app/src/main/java/com/google/firebase/example/appcheck/MainActivity.java
- appcheck/app/src/main/java/com/google/firebase/example/appcheck/kotlin/MainActivity.kt
Using the safetynet provider now throws an error during build 😬
> refactor(appcheck): replace deprecated safetynet with playintegrity

- auth/app/src/main/java/com/google/firebase/quickstart/auth/EmulatorSuite.java
- auth/app/src/main/java/com/google/firebase/quickstart/auth/kotlin/EmulatorSuite.kt
Add auth emulator snippet that is currently hardcoded in the doc.
> feat(auth): add auth emulator snippets

- auth/app/src/main/java/com/google/firebase/quickstart/auth/GenericIdpActivity.java
- auth/app/src/main/java/com/google/firebase/quickstart/auth/kotlin/GenericIdpActivity.kt
This snippet should replace the hardcoded one in https://firebase.google.com/docs/auth/android/openid-connect#manual
> add snippet for manual oidc sign-in

- inappmessaging/app/src/main/java/com/google/firebase/example/inappmessaging/MainActivity.java
- inappmessaging/app/src/main/java/com/google/firebase/example/inappmessaging/MyClickListenerBundles.java
- inappmessaging/app/src/main/java/com/google/firebase/example/inappmessaging/kotlin/MainActivity.kt
- inappmessaging/app/src/main/java/com/google/firebase/example/inappmessaging/kotlin/MyClickListenerBundles.kt
These snippets should replace the hardcoded ones in https://firebase.google.com/docs/in-app-messaging/modify-message-behavior?platform=android
> feat(fiam): add snippets for event triggers and custom bundles

- appcheck/app/build.gradle.kts
- appcheck/app/src/main/java/com/google/firebase/example/appcheck/ApiWithAppCheckExample.java
- appcheck/app/src/main/java/com/google/firebase/example/appcheck/kotlin/ApiWithAppCheckExample.kt
- appcheck/app/src/main/java/com/google/firebase/example/appcheck/kotlin/CustomProvider.kt
- appcheck/app/src/main/java/com/google/firebase/example/appcheck/kotlin/MainActivity.kt
- Limited-use token snippets
- Uss ktx more
> Update App Check snippets

- firestore/app/src/main/java/com/google/example/firestore/DocSnippets.java
- firestore/app/src/main/java/com/google/example/firestore/kotlin/DocSnippets.kt
Kotlin and Android snippets for sum and average.
> Sum and average snippets.

- .github/workflows/android.yml
This should hopefully fix #602
> ci: use ubuntu-latest
