firestore/app/src/main/java/com/google/example/firestore/DocSnippets.java, firestore/app/src/main/java/com/google/example/firestore/kotlin/DocSnippets.kt
The docs mention this flag and we use it in all the other platforms, but it was missing from Android.
Used here: https://firebase.google.com/docs/firestore/manage-data/enable-offline#listen_to_offline_data
=> Add MetadataChanges.INCLUDE to offlineListen snippet.

mlkit/app/src/main/java/com/google/firebase/example/mlkit/kotlin/BarcodeScanningActivity.kt, mlkit/app/src/main/java/com/google/firebase/example/mlkit/kotlin/ImageLabelingActivity.kt, mlkit/app/src/main/java/com/google/firebase/example/mlkit/kotlin/LandmarkRecognitionActivity.kt
The commented snippets were still in Java, although I've noticed the [documentation](https://firebase.google.com/docs/ml-kit/android/label-images) already has it in Kotlin. I suppose the documentation is not yet loading these snippets from this repo.
=> refactor: change commented snippets from java to kotlin

firestore/app/src/main/java/com/google/example/firestore/DocSnippets.java, firestore/app/src/main/java/com/google/example/firestore/kotlin/DocSnippets.kt
Starting in version 18.2.0, the Cloud Firestore Android SDK includes a `FirebaseFirestore.runBatch()` method which executes a `batchFunction` on a new `WriteBatch` and then commits all of the writes made by that `batchFunction`.
=> Demonstrate usage of FirebaseFirestore.runBatch() method

firestore/app/build.gradle, firestore/app/src/main/java/com/google/example/firestore/SolutionDeletes.java, firestore/app/src/main/java/com/google/example/firestore/kotlin/SolutionDeletes.kt
Was wondering if we could have the Android version of [Client Implementation of the Firestore Delete Solution](https://firebase.google.com/docs/firestore/solutions/delete-collections#client_invocation) on the Documentation?
=> feat: add snippets for firestore server-side deletes solution

database/app/build.gradle, dynamic-links/app/build.gradle, firebaseoptions/app/build.gradle, firestore/app/build.gradle, mlkit/app/build.gradle, mlkit/app/src/main/java/com/google/firebase/example/mlkit/CustomModelActivity.java, mlkit/app/src/main/java/com/google/firebase/example/mlkit/kotlin/CustomModelActivity.kt, perf/app/build.gradle, predictions/app/build.gradle
Currently, our automatic build is failing in #141 because MLKit v22.0.0 introduces some [breaking changes](https://firebase.google.com/support/release-notes/android#mlkit-model-interpreter_v22-0-0).
I've also noticed that in order to accommodate these changes, the [devsite](https://firebase.google.com/docs/ml-kit/android/use-custom-models) is no longer loading some of the snippets from this repository.
This PR should:
- Address the breaking changes to fix our automatic build (using snippets from the devsite);
- Add the new snippets to this repository so that the devsite can load from here again. PS: the new snippets are under the tags `mlkit_model_download_task`, `mlkit_check_download_status` and `mlkit_remote_model_download_listener`.
=> add mlkit interpreter 22.0.0 snippets

.travis.yml, admob/app/build.gradle, appindexing/app/build.gradle, auth/app/build.gradle, crash/app/build.gradle, crashlytics/app/build.gradle, database/app/build.gradle, dl-invites/app/build.gradle, dynamic-links/app/build.gradle, firebaseoptions/app/build.gradle, firestore/app/build.gradle, functions/app/build.gradle, inappmessaging/app/build.gradle, instanceid/app/build.gradle, invites/app/build.gradle, messaging/app/build.gradle, mlkit/app/build.gradle, perf/app/build.gradle, predictions/app/build.gradle, storage/app/build.gradle, tasks/app/build.gradle, test-lab/app/build.gradle
This PR should:
- Update all snippets to target SDK 29
- Add platform-29 and build-tools 29.0.0 to `.travis.yml `
=> chore: update to sdk version 29

appindexing/app/src/main/java/com/google/firebase/example/appindexing/AppIndexingUpdateService.java, appindexing/app/src/main/java/com/google/firebase/example/appindexing/kotlin/AppIndexingUpdateService.kt
`AppindexingUpdateService` had a race condition because its call to `FirebaseAppIndex#update` is asynchronous, but `IntentService#onHandleIntent` is a synchronous method. The solution is to `Tasks#await` the `Task` that `FirebaseAppindex#update` returns.
=> Fixed `AppIndexingUpdateService` race condition

firestore/app/src/main/java/com/google/example/firestore/kotlin/DocSnippets.kt
Fixed Android snippet in previous PR but I missed the Kotlin snippet.
=> Kotlin, "region" field name should be "regions"

.github/workflows/android.yml, build_pull_request.sh
Same as firebase/quickstart-android#1094
Notice that here I've also changed the order of "Install NDK" and "Check Snippets", since there's no point in installing the NDK if the build will eventually fail because of mispelled snippets.
=> chore: implement selective builds on GitHub Actions

firestore/app/src/main/java/com/google/example/firestore/kotlin/DocSnippets.kt
This should update our Kotlin snippets to use the `firestoreSettings` KTX instead of Java's `FirebaseFirestoreSettings.Builder`
=> refactor(firestore): use firestoreSettings KTX

firestore/app/build.gradle, firestore/app/src/main/java/com/google/example/firestore/kotlin/SolutionDeletes.kt
This should refactor our firestore snippets to use Functions KTX.
Btw, @samtstern I had added this snippet in #139 but it's not yet displayed on the Documentation. I hope it's not hard to add it.
=> refactor(firestore): use Functions KTX on Kotlin snippet

firebaseoptions/app/src/main/java/devrel/firebase/google/com/firebaseoptions/kotlin/MainActivity.kt
See https://firebase.google.com/docs/reference/android/com/google/firebase/FirebaseOptions.Builder#public-firebaseoptions.builder-setdatabaseurl-string-databaseurl
which doesn't use setDatabaseURL.
Also included the `.` before the commented method calls to directly allow code uncommenting
=> Change commented method call to the correct method

storage/app/src/main/java/com/google/firebase/referencecode/storage/StorageActivity.java, storage/app/src/main/java/com/google/firebase/referencecode/storage/kotlin/DownloadActivity.kt, storage/app/src/main/java/com/google/firebase/referencecode/storage/kotlin/StorageActivity.kt, storage/app/src/main/java/com/google/firebase/referencecode/storage/kotlin/UploadActivity.kt
A few things going on here:
- replace `println()` with `Log.d()` to make it consistent with other snippets.
- use `lateinit var` instead of a nullable `StorageReference`, because the initialization snippet also uses `lateinit var`.
- use the new Kotlin Destructuring Declarations (`storage-ktx:19.2.0`) for `TaskSnapshot` and `ListResult`.
- add missing arguments to lambda functions - some code comments mention variables that are not visible on the docs.
For example, in the snippet bellow `taskSnapshot` is not visible
https://github.com/firebase/snippets-android/blob/7695c5ee6589377a40ca8f70c70d6527c5a49897/storage/app/src/main/java/com/google/firebase/referencecode/storage/kotlin/StorageActivity.kt#L149-L154
- replace empty `MetadataBuilder` with its ktx equivalent
=> refactor(storage): improve code snippets

firestore/app/src/main/java/com/google/example/firestore/kotlin/DocSnippets.kt
As mentioned in StackOverflow answers [1](https://stackoverflow.com/a/52268330/5861618) and [2](https://stackoverflow.com/a/52285505/5861618): when using Kotlin's `data class` in firestore, we need to add the `@field:JvmField` annotation to boolean fields prefixed with 'is', otherwise the Firebase SDK Snapshot parser always returns the default value.
This PR should add that annotation to our Docs, as suggested in [this comment](https://stackoverflow.com/questions/46406376/kotlin-class-does-not-get-its-boolean-value-from-firebase#comment95933719_52268330).
=> refactor(firestore): add JvmField annotation to kotlin POJO snippet

auth/app/src/main/java/com/google/firebase/quickstart/auth/MainActivity.java, auth/app/src/main/java/com/google/firebase/quickstart/auth/kotlin/MainActivity.kt
This PR should address the recent deprecation from [Auth 20.0.0](https://firebase.google.com/support/release-notes/android#auth_v20-0-0)
=> refactor(auth): replace deprecated phone auth usage

admob/app/build.gradle, admob/app/src/main/java/com/google/firebase/example/admob/MainActivity.java, admob/app/src/main/java/com/google/firebase/example/admob/kotlin/MainActivity.kt, admob/app/src/main/res/layout/activity_main.xml, admob/app/src/main/res/values/strings.xml
As discussed in firebase/quickstart-android#1247, we're moving the admob snippets to this repo.
Snippets added in this PR:
<table>
<tr>
<th>Filename</th>
<th>Snippets added</th>
</tr>
<tr>
<td>MainActivity.kt</td>
<td>
ads_on_create,load_banner_ad, instantiate_interstitial_ad, create_interstitial_ad_listener, display_interstitial_ad, request_new_interstitial, add_lifecycle_methods
</td>
</tr>
<tr>
<td>MainActivity.java</td>
<td>ads_on_create,load_banner_ad, instantiate_interstitial_ad, create_interstitial_ad_listener, display_interstitial_ad, request_new_interstitial, add_lifecycle_methods</td>
</tr>
<tr>
<td>activity_main.xml</td>
<td>define_ad_layout</td>
</tr>
<tr>
<td>build.gradle</td>
<td>gradle_play_config</td>
</tr>
</table>
There are snippets in AndroidManifest.xml which were kept …
=> refactor(admob): add snippets from quickstart-android

auth/app/src/main/java/com/google/firebase/quickstart/auth/AnonymousAuthActivity.java, auth/app/src/main/java/com/google/firebase/quickstart/auth/CustomAuthActivity.java, auth/app/src/main/java/com/google/firebase/quickstart/auth/EmailPasswordActivity.java, auth/app/src/main/java/com/google/firebase/quickstart/auth/FacebookLoginActivity.java, auth/app/src/main/java/com/google/firebase/quickstart/auth/GoogleSignInActivity.java, auth/app/src/main/java/com/google/firebase/quickstart/auth/MultiFactorActivity.java, auth/app/src/main/java/com/google/firebase/quickstart/auth/PhoneAuthActivity.java, auth/app/src/main/java/com/google/firebase/quickstart/auth/kotlin/AnonymousAuthActivity.kt, auth/app/src/main/java/com/google/firebase/quickstart/auth/kotlin/CustomAuthActivity.kt, auth/app/src/main/java/com/google/firebase/quickstart/auth/kotlin/EmailPasswordActivity.kt, auth/app/src/main/java/com/google/firebase/quickstart/auth/kotlin/FacebookLoginActivity.kt, auth/app/src/main/java/com/google/firebase/quickstart/auth/kotlin/GoogleSignInActivity.kt, auth/app/src/main/java/com/google/firebase/quickstart/auth/kotlin/MultiFactorActivity.kt, auth/app/src/main/java/com/google/firebase/quickstart/auth/kotlin/PhoneAuthActivity.kt
As part of firebase/quickstart-android#1217, this should move the auth snippets from the quickstart repo to this one.
All snippet names remain the same, and the file names are also the same.
=> feat(auth): move snippets from quickstart-android

firestore/app/src/main/java/com/google/example/firestore/SolutionBundles.java, firestore/app/src/main/java/com/google/example/firestore/kotlin/SolutionBundles.kt
Android snippets for:
https://firebase.google.com/docs/firestore/solutions/serve-bundles
=> Add Firestore bundles snippets

functions/app/src/main/java/devrel/firebase/google/com/functions/MainActivity.java, functions/app/src/main/java/devrel/firebase/google/com/functions/kotlin/MainActivity.kt
Fix the incorrect emulator IP in functions emulator sample codes.
Previous code caused the below error.
```
Caused by: java.net.UnknownHostException: Unable to resolve host "10.0.2.2.": No address associated with hostname
```
=> Fix incorrect emulator host IP address

admob/app/build.gradle, analytics/app/build.gradle, appindexing/app/build.gradle, auth/app/build.gradle, crashlytics/app/build.gradle, database/app/build.gradle, dl-invites/app/build.gradle, dl-invites/app/src/main/java/com/google/firebase/dynamicinvites/kotlin/view/AdvancedActivity.kt, dl-invites/app/src/main/java/com/google/firebase/dynamicinvites/kotlin/view/MainActivity.kt, dl-invites/app/src/main/java/com/google/firebase/dynamicinvites/kotlin/view/ShareDialogFragment.kt, dynamic-links/app/build.gradle, firebaseoptions/app/build.gradle, firestore/app/build.gradle, functions/app/build.gradle, inappmessaging/app/build.gradle, installations/app/build.gradle, messaging/app/build.gradle, mlkit/app/build.gradle, perf/app/build.gradle, predictions/app/build.gradle, predictions/app/src/main/java/com/google/firebase/example/predictions/kotlin/MainActivity.kt, storage/app/build.gradle, storage/app/src/main/java/com/google/firebase/referencecode/storage/kotlin/StorageActivity.kt, tasks/app/build.gradle, test-lab/app/build.gradle
This should fix #289 
There's also an unrelated change that I spotted when doing this, so it ended up in this PR: replaced an if-else with the elvis operator in `dl-invites/ShareDialogFragment.kt`
=> refactor(*): remove kotlin-android-extensions

admob/build.gradle, analytics/build.gradle, appcheck/build.gradle, appindexing/build.gradle, auth/build.gradle, build.gradle, crashlytics/app/build.gradle, crashlytics/build.gradle, database/build.gradle, dl-invites/build.gradle, dynamic-links/build.gradle, firebaseoptions/build.gradle, firestore/app/build.gradle, firestore/build.gradle, functions/build.gradle, inappmessaging/build.gradle, installations/app/build.gradle, installations/app/google-services.json, installations/build.gradle, messaging/build.gradle, ml-functions/build.gradle, mlkit/build.gradle, perf/app/build.gradle, perf/build.gradle, predictions/build.gradle, storage/build.gradle, tasks/app/build.gradle, tasks/app/google-services.json, tasks/build.gradle, test-lab/build.gradle
This Pull Request replaces all references of `jcenter()` in the Android snippets by `mavenCentral()`, since `jcenter()` repo is now deprecated. All snippets have been tested on an emulator, but some of them were crashing right after the launch due to missing plugins and/or outdated libraries. These updates/fixes were made in specific commits and now all snippets are running.
=> Replace jcenter by mavencentral

analytics/app/build.gradle, analytics/app/src/main/java/com/google/firebase/example/analytics/MainActivity.java, analytics/app/src/main/java/com/google/firebase/example/analytics/kotlin/MainActivity.kt, analytics/settings.gradle
feature: added 3rd party sample`ad_impression` snippets for both Kotlin and Java to address issue #324 
added 3rd Party libraries so that the project will build and show the snippets in the correct format including "override" modifier.
=> Add impression snippets for java and kotlin 324

database/app/src/main/java/com/google/firebase/referencecode/database/kotlin/ReadAndWriteSnippets.kt
Replacing `HashMap()` with `hashMapOf()` to make it consistent with the [other snippets](https://github.com/firebase/snippets-android/search?q=hashMapOf).
=> rtdb: replace HashMap() with hashMapOf()

messaging/app/src/main/java/com/google/firebase/example/messaging/MainActivity.java, messaging/app/src/main/java/com/google/firebase/example/messaging/kotlin/MainActivity.kt
=> refactor(fcm): let the system manage the POST_NOTIFICATIONS Request Code

messaging/app/src/main/java/com/google/firebase/example/messaging/MainActivity.java, messaging/app/src/main/java/com/google/firebase/example/messaging/kotlin/MainActivity.kt
Instead of omitting the `@RequiresApi(33)` annotation in our docs, it might be better for developers if we show them how to check the API level during runtime before requesting the `POST_NOTIFICATIONS` permission.
=> check API Level in runtime before requesting notifications permission

messaging/app/src/main/java/com/google/firebase/example/messaging/MyFirebaseMessagingService.java, messaging/app/src/main/java/com/google/firebase/example/messaging/kotlin/MyFirebaseMessagingService.kt
Reported in #377 
I missed this method when I ported the fcm snippets from quickstart-android in #351
=> feat(fcm): add missing sendNotification() method

build.gradle
Sometimes dpebot opens PRs to update these 3rd party dependencies, which doesn't really add value to our repo (see #385 for example). This PR should add both dependencies to our blocklist so that dpebot stops updating them.
We can update them manually if we ever need to change their corresponding snippets.
=> add applovin and ironsource to dpebot's blocklist

firestore/app/build.gradle
This dependency was originally added to work around an error with an outdated version of okhttp (see https://stackoverflow.com/a/68231205/5861618).
Firestore has now updated their okhttp version, so we no longer need to explicitly set this.
=> chore(firestore): remove explicit grpc-oktthp dependency

admob/build.gradle, analytics/build.gradle, auth/build.gradle, build.gradle, config/build.gradle, crashlytics/build.gradle, database/build.gradle, dl-invites/build.gradle, dynamic-links/build.gradle, firebaseoptions/build.gradle, firestore/build.gradle, functions/build.gradle, inappmessaging/build.gradle, installations/build.gradle, messaging/build.gradle, ml-functions/build.gradle, mlkit/build.gradle, perf/build.gradle, storage/build.gradle, tasks/build.gradle, test-lab/build.gradle
Reverts firebase/snippets-android#404
According to the [release notes](https://github.com/JetBrains/kotlin/releases/tag/v1.7.22), this version is a "technical release". I'm not sure what that means, but apparently it doesn't contain any relevant fix from 1.7.21.
=> Revert "Auto-update dependencies."

analytics/app/src/main/java/com/google/firebase/example/analytics/MainActivity.java, analytics/app/src/main/java/com/google/firebase/example/analytics/kotlin/MainActivity.kt
MainActivity.kt and MainActivity.java implements `onResume` to record the screen state instead of calling the` recordScreenView` on the `onCreate` function.
=> (analytics) implement - saving screen state using onResume

auth/app/src/main/java/com/google/firebase/quickstart/auth/MainActivity.java, auth/app/src/main/java/com/google/firebase/quickstart/auth/PhoneAuthActivity.java, database/app/src/main/java/com/google/firebase/referencecode/database/MainActivity.java, database/app/src/main/java/com/google/firebase/referencecode/database/OfflineActivity.java, database/app/src/main/java/com/google/firebase/referencecode/database/QueryActivity.java, database/app/src/main/java/com/google/firebase/referencecode/database/ReadAndWriteSnippets.java, firestore/app/src/main/java/com/google/example/firestore/DocSnippets.java, firestore/app/src/main/java/com/google/example/firestore/SolutionAggregation.java
This PR should add nullability annotations to some of our java snippets.
Their absence doesn't really break any code, but adding it prevents the IDE from showing warnings that some variable might be null.
=> refactor(auth, database, firestore): add nullability annotations to java snippets

messaging/app/build.gradle, messaging/app/src/main/java/com/google/firebase/example/messaging/kotlin/MainActivity.kt, messaging/functions/index.js
Copying the snippets from https://github.com/firebase/quickstart-android/pull/1453 to this repo so that they can be added to the docs.
Having these snippets on the other repo makes it harder to maintain the samples. Having them on this repo instead should be safer.
=> add snippets to demonstrate fcm registration tokens best practices

.github/workflows/android.yml, admob/app/build.gradle, analytics/app/build.gradle, appcheck/app/build.gradle, auth/app/build.gradle, build.gradle, config/app/build.gradle, crashlytics/app/build.gradle, database/app/build.gradle, dl-invites/app/build.gradle, dynamic-links/app/build.gradle, firebaseoptions/app/build.gradle, firestore/app/build.gradle, functions/app/build.gradle, gradle.properties, gradle/wrapper/gradle-wrapper.properties, inappmessaging/app/build.gradle, installations/app/build.gradle, messaging/app/build.gradle, perf/app/build.gradle, storage/app/build.gradle, tasks/app/build.gradle, test-lab/app/build.gradle
This PR should upgrade the project to use AGP 8.0
=> chore: upgrade to AGP 8.0

messaging/app/src/main/java/com/google/firebase/example/messaging/MyFirebaseMessagingService.java, messaging/app/src/main/java/com/google/firebase/example/messaging/kotlin/MyFirebaseMessagingService.kt
Add small icon when creating a new notification for both java and kotlin services, to avoid crashing.
=> Add small icon to java and kotlin messaging services

analytics/app/build.gradle.kts, analytics/app/src/main/java/com/google/firebase/example/analytics/kotlin/MainActivity.kt
Now that firebase/firebase-android-sdk#5457 has been fixed, we can finally migrate analytics out of ktx
=> refactor(analytics): migrate out of KTX

.github/workflows/android.yml
CI started [breaking](https://github.com/firebase/snippets-android/actions/runs/7610154648/job/20722905877?pr=521) due to https://github.com/actions/runner-images/issues/8952
Specifically, the "Install NDK" step would fail with the following error:
```
sudo: a terminal is required to read the password; either use the -S option to read from standard input or configure an askpass helper
sudo: a password is required
```
This PR should fix it by using Android's "Command-line tools" rather than the "SDK tools".
=> ci: use cmdline-tools instead of sdk tools

build.gradle.kts
Firebase has started to release `alpha` and `beta` artifacts. We should let the bot update these dependencies to keep our quickstarts up to date.
=> chore(*): allow alpha and beta updates for Firebase libraries

.github/workflows/android.yml
=> ci: use ubuntu-22.04 instead of ubuntu-latest

crashlytics/app/build.gradle.kts, crashlytics/app/src/main/java/com/google/firebase/example/crashlytics/MainActivity.java, crashlytics/app/src/main/java/com/google/firebase/example/crashlytics/kotlin/MainActivity.kt
Ref - https://github.com/firebase/firebase-android-sdk/pull/6528
=> Add examples to use the new recordException overload.

.github/workflows/android.yml
This PR should:
- Update `actions/setup-java@v1` -> `actions/setup-java@v4`
Note that v4 asks for a distribution to be specified. `temurin` is the one used by our SDKs: https://github.com/firebase/firebase-android-sdk/blob/0ce193f352d44be79b976b48b9a2e79c4caedbdf/.github/workflows/build-release-artifacts.yml#L21
- Update `actions/checkout@v2` -> `actions/checkout@v4`
- Move "Check Snippets" to be the first step.
- Remove the "Install NDK" step, which was only necessary for the MLKit snippets, which we no longer build since #424.
=> ci: update actions versions and remove NDK install

build.gradle.kts, functions/app/build.gradle.kts
dpebot keeps trying to bump the Firebase BoM in the Functions quickstart, but runs into a build error due to firebase/firebase-android-sdk#6522
This PR should pin the Functions SDK version to the last working one before the break.
Once a new version of functions comes out with the fix for firebase/firebase-android-sdk#6522 we should revert this change.
=> pin the functions SDK version

auth/app/build.gradle.kts, auth/app/src/main/java/com/google/firebase/quickstart/auth/GoogleSignInActivity.java, auth/app/src/main/java/com/google/firebase/quickstart/auth/kotlin/GoogleSignInActivity.kt
This PR:
- Removes Google One Tap sign-in, which is deprecated
- Adds Credential Manager, which is the recommended way to fetch users' credentials
=> Add Credential Manager to Auth samples

functions/app/build.gradle.kts, functions/app/src/main/java/devrel/firebase/google/com/functions/MainActivity.java, functions/app/src/main/java/devrel/firebase/google/com/functions/kotlin/MainActivity.kt
These will be added to https://firebase.google.com/docs/functions/callable
=> feat: add streaming functions snippets
